[package]
name = "scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["blocking"] }
scraper = "0.19.0"
csv = "1.1"
tokio = { version = "1", features = ["full"] }